name: 'delete-test'
on:
  pull_request:
    types: [closed]

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          name: 'tenant1'
          hasuraCloudGraphQLEndpoint: 'https://8109-106-51-72-39.ngrok.io/v1/graphql'
          delete: true
          ephemeralDBConfig: |
            POSTGRES_SERVER_CONNECTION_URI=${{secrets.DO_PG_STRING}}
            PG_ENV_VARS_FOR_HASURA=CUSTOM_DB_1,CUSTOM_DB_2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          HASURA_CLOUD_ACCESS_TOKEN: ${{secrets.HASURA_CLOUD_ACCESS_TOKEN}}
