name: 'build-test'
on:
  pull_request:
    types: [open, reopen, synchronize]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  preview: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Debug
        uses: hmarr/debug-action@v2
      - uses: ./
        with:
          name: 'hc-preview-app-internal${{github.event.number}}'
          hasuraCloudGraphQLEndpoint: 'https://cb24-116-73-105-66.ngrok.io/v1/graphql'
          hasuraProjectDirectoryPath: hasura
          region: 'us-east-2'
          hasuraEnv: |
            HASURA_GRAPHQL_CORS_DOMAIN=*
          postgresDBConfig: |
            POSTGRES_SERVER_CONNECTION_URI=${{secrets.DO_PG_STRING}}
            PG_ENV_VARS_FOR_HASURA=PG_DATABASE_URL
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          HASURA_CLOUD_ACCESS_TOKEN: "JKejuYriP3Om9ROiYn9hctovPMyX0VTUpm2Ov3AS7OxbJ7tJ4GBcDE3suiTD8Fp1"
          ACTIONS_RUNNER_DEBUG: true
