name: 'build-test'
on:
  pull_request:
    types: [open, reopen, synchronize]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  preview: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          name: 'tenant1'
          hasuraCloudGraphQLEndpoint: 'https://8109-106-51-72-39.ngrok.io/v1/graphql'
          hasuraProjectDirectoryPath: hasura
          hasuraEnv: |
            HASURA_GRAPHQL_CORS_DOMAIN=*
            PG_DB_URL=posg.....
          postgresDBConfig: |
            POSTGRES_SERVER_CONNECTION_URI=${{secrets.DO_PG_STRING}}
            PG_ENV_VARS_FORR_HASURA=CUSTOM_DB_1,CUSTOM_DB_2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          HASURA_CLOUD_ACCESS_TOKEN: ${{secrets.HASURA_CLOUD_ACCESS_TOKEN}}
