name: 'build-test'
on:
  pull_request:
    types: [open, reopen, synchronize]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  preview: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Debug
        uses: hmarr/debug-action@v2
      - uses: ./
        with:
          name: 'hc-preview-app-internal${{github.event.number}}'
          hasuraCloudGraphQLEndpoint: 'https://data.pro.arusah.com/v1/graphql'
          hasuraProjectDirectoryPath: hasura
          region: 'ap-south-1'
          hasuraEnv: |
            HASURA_GRAPHQL_CORS_DOMAIN=*
            PG_DATABASE_URL=pgsomething

        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          HASURA_CLOUD_ACCESS_TOKEN: ${{secrets.HASURA_CLOUD_ACCESS_TOKEN}}
          ACTIONS_RUNNER_DEBUG: true
